### ISSUE TITLE
The script doesnt work when we initially log in.

### ISSUE THREAD

**Issue by achidipothu** [tuhlmann/select-howdy-source#1]
on a fresh boot, at the login, it tries to use the non active laptop camera and this leads to detection failure.
afterwards it works great and switches the camera perfectly.

Thanks for this script, it made my life much much better. thank you. :smile:

**Comment by tuhlmann** [comment]
Thanks for letting me know!
Unfortunately I can't use howdy any longer, I'm sorry I won't be able to fix it.

Thanks,
Torsten.
